<a href="https://colab.research.google.com/github/Evora-21805468/IA-2021/blob/main/aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Criar arrays
my_array = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

print('the dimension of my_array is:', my_array.shape)
print('the type of my_array is:', my_array.dtype)

my_array_zeros = np.zeros((3,4))
print(my_array_zeros)

my_array_ones = np.ones((3,4))
print(my_array_ones)

the dimension of my_array is: (3, 3)
the type of my_array is: int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# Vectorized operations between arrays and scalars
# What happens if we represent a vector as a native list and want to add five to each element
l = [1,2,3,4,5]
try:
  l + 5
except TypeError:
  print('Cannot do this, incompatible types.')

Cannot do this, incompatible types.


In [17]:
my_l = np.array([1,2,3,4,5])
my_l + 5 # Agora sim já conseguimos somar 5 a cada elemento da lista, não foi preciso for pq foi logo direto

array([ 6,  7,  8,  9, 10])

In [19]:
# selecionar e cortar arrays de uma dimensão
my_array = np.array([1,2,3,4,5,6,7])

# ver o primeiro elemento
print('the first element of my array is:', my_array[0])

# ver os 3 primeiros
print('the first 3 elements of my array are:', my_array[0:3]) # antes dos dois ponts (:) é inclusive, depois é exclusive ou seja vai de 0 a 2

# ver desde o 2º ao 4º
print('the 2nd to 4th elements of my array are:', my_array[1:4])

# ver o ultimo elemento sem saber o tamanho do array
print('the last element of my array is:', my_array[-1])

# ver os 3 ultimos sem saber o tamanho do array 
print('the last 3 elements of my array are:', my_array[-3])

# ver os 3 primeiros sem saber o tamanho
print('the first 3 elements of my array are:', my_array[:3])

the first element of my array is: 1
the first 3 elements of my array are: [1 2 3]
the 2nd to 4th elements of my array are: [2 3 4]
the last element of my array is: 7
the last 3 elements of my array are: 5
the first 3 elements of my array are: [1 2 3]


In [27]:
# Cortar array de duas dimensões
my_array2 = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]
])

# cortar a primeira fila
print('the first row is', my_array2[0])

# cortar a primeira coluna
print('the first column is', my_array2[:,0])

# cortar as primeiras duas filas e as duas primeiras colunas
print('the selection in the comment above', my_array2[:2,:2])

# cortar a ultima coluna, 2ª e 3ª fila
print('the selection in the comment above', my_array2[1:3,-1])

the first row is [1 2 3 4]
the first column is [ 1  5  9 13]
the selection in the comment above [[1 2]
 [5 6]]
the selection in the comment above [ 8 12]


In [32]:
# vamos assumir que temos 7 sujeitos na nossa estrutura de dados retangular
names = np.array(['helen','mary','lucy','matt','linsday','ben','luke'])
genders = np.array(['f','f','f','m','f','m','m'])

# vamos criar uma matriz teste de inteiros que tem sete filas e 5 colunas
d = np.arange(35).reshape((7,5))
print(d, '\n')


# agora vamos criar a versão booleana d géneros onde feminino é True (Verdade)
sel_f = genders == 'f'
print('the sub matrix of females:','\n', d[sel_f], '\n')

# vamos corresponder o valor zero nas filas que correspondem ao género masculino
sel_m = genders != 'f'
d[sel_m] = 0
print('After assigning males the value 0 we get:','\n', d, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]] 

the sub matrix of females: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [20 21 22 23 24]] 

After assigning males the value 0 we get: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  0  0  0  0]
 [20 21 22 23 24]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]] 



In [33]:
# Fancy indexing
d[[0,2,3]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0]])

In [34]:
#1D correspondência a um corte? (slice assignment)
my_array = np.zeros(10)
my_array[3:6] = -1
print('assignment on slice is broadcast')
print(my_array)

assignment on slice is broadcast
[ 0.  0.  0. -1. -1. -1.  0.  0.  0.  0.]


In [37]:
# vamos ver como a transposing funciona numa matriz
my_array = np.arange(32).reshape(8,4)
print('the original matrix is', '\n', my_array, '\n')

mt = my_array.T #transposing sintaxe: matriz.T
print('the transposed matrix is', '\n', mt, '\n')

the original matrix is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

the transposed matrix is 
 [[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]] 



In [39]:
# funções universais unárias do Numpy

my_array = np.arange(10)
print('original array:\n', my_array, '\n')

print('The squareroot of the array is \n', np.sqrt(my_array), '\n\n')

print('The array times 4 is \n', my_array*4, '\n')


original array:
 [0 1 2 3 4 5 6 7 8 9] 

The squareroot of the array is 
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 


The array times 4 is 
 [ 0  4  8 12 16 20 24 28 32 36] 



In [42]:
# funções universais binárias
x = np.random.randn(4)
y = np.random.randn(4)

print('x is ', x, '\n')
print('y is ', y, '\n')

print('the array of per-component max value is: \n', np.maximum(x,y))


x is  [ 1.83427718 -2.54219608 -2.33286217  0.3841998 ] 

y is  [-0.38721022  1.76044959 -2.3415741   2.05686983] 

the array of per-component max value is: 
 [ 1.83427718  1.76044959 -2.33286217  2.05686983]


In [51]:
# sorting numpy arrays

my_array = np.random.randn(6)

print('original 1D array has \n', my_array, '\n')

my_array.sort() # ATENÇÃO, SÓ ORDENA NO ARRAY ORIGINAL NÃO DEVOLVE NADA
print('sorted 1D array has \n', my_array, '\n')

my_array = np.random.randn(25).reshape((5,5))
print('original 2D array has: \n', my_array, '\n')

print('sort the columns:')
my_array.sort(0) # ZERO quer dizer que vai dar preferência a ordenar os valores das COLUNAS da matriz (duvida)
print(my_array, '\n')

print('sort the rows:')
my_array.sort(1) # UM quer dizer que vai dar preferência a ordenar os valores das FILAS da matriz
print(my_array, '\n')


# os sorts parecem estranhos depois de feito, dont worry pq há valores negativos (IMPORTANT DETAIL!)

original 1D array has 
 [ 0.28512839 -0.67635986 -0.19677522  0.9042536   0.07041535 -0.91674831] 

sorted 1D array has 
 [-0.91674831 -0.67635986 -0.19677522  0.07041535  0.28512839  0.9042536 ] 

original 2D array has: 
 [[-0.84254481 -1.09608164 -1.18763432  0.23320961  0.8994474 ]
 [-1.11546671  0.01346432 -0.49684784  0.18618257  2.42111341]
 [-0.45963141  0.91643365 -0.37190585  0.85790124 -1.17163705]
 [-0.49935383  2.37044352  0.18566258 -0.02818883 -0.20620777]
 [ 1.06131325 -0.95091368 -1.05693786 -0.17169263  0.33238122]] 

sort the columns:
[[-1.11546671 -1.09608164 -1.18763432 -0.17169263 -1.17163705]
 [-0.84254481 -0.95091368 -1.05693786 -0.02818883 -0.20620777]
 [-0.49935383  0.01346432 -0.49684784  0.18618257  0.33238122]
 [-0.45963141  0.91643365 -0.37190585  0.23320961  0.8994474 ]
 [ 1.06131325  2.37044352  0.18566258  0.85790124  2.42111341]] 

sort the rows:
[[-1.18763432 -1.17163705 -1.11546671 -1.09608164 -0.17169263]
 [-1.05693786 -0.95091368 -0.84254481 -0.2062

In [59]:
import pandas as pd

sx = pd.Series([1,2,-9,0])
print('my first pandas series is', sx, '\n')

print('A series has values \n', sx.values)
print('A series has index \n', sx.index)

sx.index =['a','b','c','d'] # podemos redefinir os indices de um dataframe
print(sx, '\n')
print('A series has new indexes \n', sx.index)

print('In my sx the element with index a is:', sx['a'], '\n')

print('Boolean indexing? No problem!\n', sx[[True,False,False,True]],'\n')

print('Fancy indexing? No problem! \n', sx[['a','d']],'\n')

print('check for index in series, no problem')

# INACABADO (VER FICHA MOODLE)

my first pandas series is 0    1
1    2
2   -9
3    0
dtype: int64 

A series has values 
 [ 1  2 -9  0]
A series has index 
 RangeIndex(start=0, stop=4, step=1)
a    1
b    2
c   -9
d    0
dtype: int64 

A series has new indexes 
 Index(['a', 'b', 'c', 'd'], dtype='object')
In my sx the element with index a is: 1 

Boolean indexing? No problem!
 a    1
d    0
dtype: int64 

Fancy indexing? No problem! 
 a    1
d    0
dtype: int64 

