<a href="https://colab.research.google.com/github/Evora-21805468/IA-2021/blob/main/Aula2_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial 2

## Numpy

The fundamental package for scientific computing with Python

<img src="https://numpy.org/images/logos/numpy.svg" width="100" height="100">

[NumPy](https://numpy.org/)

In [1]:
import numpy as np

### Exercicio 1 

1. Use a função arange de numpy para criar um vetor chamado my_array com a sequencia de números desde zero até 24.

In [36]:
my_array = np.arange(24)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

**Reminder**   
The built-in type ```range```

*The range type represents an immutable sequence of numbers and is commonly used for looping a specific number of times in for loops.*[[source]](https://docs.python.org/3.3/library/stdtypes.html?highlight=range#ranges)


```python
range(stop) -> range object
range(start, stop[, step]) -> range object
```

In [ ]:
# Ex 1.1

2. Use a função reshape para redimensionar o vetor de tal forma que fique com seis filas e quatro colunas. Que acontece? Qual é a relação entre número de elementos e a dimensão duma matrix bi-dimensional?

In [44]:
my_array.reshape(6,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Ex 1.2

3. Sendo que temos 24 elementos, identifique duas combinações de dimensões que permitam redimensionar este vector em forma de matriz.

In [45]:
my_array.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
# Ex 1.2

## Pergunta 2

Considere a função da similaridade de coseno com a qual trabalhamos no último laboratório:

$$
  cos(v1, v2) = \frac{v1 . v2}{\lVert v1 \rVert \times \lVert v2 \rVert}
$$  

Investigar o uso das funções `linalg.norm` e `dot` dentro de Numpy para re-escrever a função sem usar qualquer `for` loop.

In [20]:
v1 = [1,2,3,4]
v2 = [3,2,5,4]

# Ex 2

In [21]:
a = (np.dot(v1,v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))
a

0.9441175904999112

In [ ]:
# Result

0.9441175904999112

## Pergunta 3

$$\begin{bmatrix} 
1 & 2 & 1 & 7 \\ 
3 & 0 & 1 & 8 \\ 
0 & 2 & 4 & 9 \\ 
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Criar esta matriz em numpy
2. Slice a primeira coluna inteira
3. Slice a primeira coluna mas apenas as filas 2 e 3
4. Slice os quatro elementos no centro da matriz
5. Slice a sub-matriz dos quatro elementos no canto inferior direito, sem usar o tamanho da matriz
6. Slice a sub-matriz dos quatro elementos no canto superior direito, sem usar o tamanho da matriz


In [50]:
# Pergunta 3.1: criação da matriz como objeto de numpy
my_array2 = np.array([
  [1,2,1,7],
  [3,0,1,8],
  [0,2,4,9],
  [2,2,5,5]
])

# Pergunta 3.2: primeira coluna, 
# não há necessidade de saber as dimensões da matriz

my_array2[:,0]

# Pergunta 3.3: slice primeira coluna mas so as filas 2 e 3
# não há necessidade de saber as dimensões da matriz

my_array2[1:3,0]

# Pergunta 3.4: slice os quatro elementos no centro da matriz
# este slice usa o conhecimento do tamanho da matriz
# no caso geral será necessário escrever uma função que determine
# o slice

my_array2[1:3,1:3]

# Pergunta 3.5.1: slice a sub-matriz dos quatro elementos no canto inferior 
# direito, sem usar o tamanho da matriz.
# esta versão não cumpre o requerimento, porque conta desde o início da matriz
# e portanto está a usar informação do tamanho da mesma para atingir o
# objetivo

my_array2[2:,2:]

# Pergunta 3.5.2: slice a sub-matriz dos quatro elementos no canto inferior 
# direito, sem usar o tamanho da matriz.
# esta versão sim cumpre o requerimento, porque define o slice desde o fim
# da matriz

my_array2[-2:,-2:]

# Pergunta 3.6: slice a sub-matriz dos quatro elementos no canto inferior 
# direito, sem usar o tamanho da matriz.

my_array2[0:FIM, 0:FIM]


array([[4, 9],
       [5, 5]])

In [ ]:
# Result

first column: 
 [1 3 0 2] 

first column, rows 2 and 3: 
 [3 0] 

centre: 
 [[0 1]
 [2 4]] 

bottom right: 
 [[4 9]
 [5 5]] 

top right: 
 [[1 7]
 [1 8]] 

top right: 
 [[1 7]
 [1 8]] 

bottom right: 
 [[4 9]
 [5 5]] 

top right: 
 [[1 7]
 [1 8]] 



## Pergunta 4

Dado o ficheiro json de teste, carregue o mesmo num Pandas dataframe

In [51]:
import pandas as pd

### 4.1 Reading the data locally

In [53]:
path = '../data/A2_user_details.json'

# Ler o ficheiro json e fazer output do resultado

### 4.2 Reading the data on Google Drive within Google Colab

In [61]:
from google.colab import drive
drive.mount('/content/drive')

# o vosso path para o ficheiro poderá ser diferente 
path = '/content/drive/MyDrive/data/A2_user_details.json'

# Ler o ficheiro json e fazer output do resultado
df = pd.read_json(path)
df


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


id  user_id  ...  last_modified_by    last_modified_date
0   1136     1128  ...     anonymousUser  2019-05-08T12:48:28Z
1   1074     1050  ...     anonymousUser  2019-05-08T12:42:48Z
2    987      986  ...     anonymousUser  2019-05-08T12:26:18Z
3    988      987  ...     anonymousUser  2019-05-08T12:29:30Z
4    989      988  ...     anonymousUser  2019-05-08T12:30:02Z
..   ...      ...  ...               ...                   ...
93  1842     1841  ...     anonymousUser  2019-05-09T12:14:21Z
94  1844     1855  ...     anonymousUser  2019-05-09T12:14:59Z
95  1127     1096  ...     anonymousUser  2019-05-08T12:46:26Z
96  1864     1878  ...     anonymousUser  2019-05-09T12:23:35Z
97  1880     2875  ...     anonymousUser  2019-05-09T13:28:00Z

[98 rows x 12 columns]

### 4.2 Mantenha unicamente as seguintes colunas:

1. user_id
2. institution_id
3. age
4. gender

In [64]:
# P4.2

dfx = df[['user_id','institution_id','age','gender']]
dfx


user_id  institution_id  age  gender
0      1128               9   18    MALE
1      1050               7   16  FEMALE
2       986               1   17  FEMALE
3       987               1   16  FEMALE
4       988               1   16  FEMALE
..      ...             ...  ...     ...
93     1841               2   17  FEMALE
94     1855               2   17  FEMALE
95     1096               7   20    MALE
96     1878               2   17    MALE
97     2875               4   16  FEMALE

[98 rows x 4 columns]

## Pergunta 5

### 5.1
Selecione os `user_id` das raparigas com idade 17 anos ou mais e guarde numa variáevel `fids`. Esta variável, é um `Series` ou um `DataFrame`

In [71]:
# P5.1

mask_female = dfx['gender'] == 'FEMALE' 
mask_age = dfx['age'] >= 17
maskfinal = mask_female & mask_age

dfx[maskfinal]

user_id  institution_id  age  gender
2       986               1   17  FEMALE
6       990               1   18  FEMALE
8       992               1   17  FEMALE
17     1005               7   17  FEMALE
19     1007               7   17  FEMALE
23     1112               7   17  FEMALE
26     1032               7   17  FEMALE
28     1151               9   18  FEMALE
29     1839               2   18  FEMALE
30     1035               7   17  FEMALE
36     3080               4   18  FEMALE
37     1047               7   17  FEMALE
38     1048               7   17  FEMALE
39     3107               4   17  FEMALE
44     3114               4   17  FEMALE
45     1077               7   17  FEMALE
52     1842               2   17  FEMALE
54     1861               2   17  FEMALE
75     1131               7   17  FEMALE
77     1115               7   17  FEMALE
93     1841               2   17  FEMALE
94     1855               2   17  FEMALE

### 5.2
Selecione os `gender` dos estudantes das escolas 1 e 2 com maiores de 17 anos

In [76]:
# P5.2
mask_institution = (dfx['institution_id'] == 1) | (dfx['institution_id'] == 2)
mask_age = dfx['age'] >= 17
maskfinal = mask_institution & mask_age

dfx[maskfinal]['gender'].value_counts()

FEMALE    8
MALE      2
Name: gender, dtype: int64

### 5.3
Adicione uma columa "scores" com valores aleatórios entre 10 e 20 para todos os alunos no dataframe

In [ ]:
#P5.3



user_id  institution_id  age  gender  scores
0      1128               9   18    MALE      12
1      1050               7   16  FEMALE      16
2       986               1   17  FEMALE      16
3       987               1   16  FEMALE      15
4       988               1   16  FEMALE      13
..      ...             ...  ...     ...     ...
93     1841               2   17  FEMALE      11
94     1855               2   17  FEMALE      12
95     1096               7   20    MALE      16
96     1878               2   17    MALE      16
97     2875               4   16  FEMALE      11

[98 rows x 5 columns]

## Pergunta 6

Execute o comando

```python
dfx.describe()
```
e descreva o resultado e a sua utilidade, após investigar o que esta função do Pandas devolve.

In [ ]:
dfx.describe()

user_id  institution_id        age
count    98.000000       98.000000  98.000000
mean   1830.428571        5.193878  16.132653
std     836.381443        2.775661   3.862689
min     986.000000        1.000000   3.000000
25%    1077.500000        2.000000  16.000000
50%    1838.500000        4.000000  16.000000
75%    2855.750000        7.750000  17.000000
max    3127.000000        9.000000  30.000000